# Generated by Django 6.0.7 on 2026-07-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
