# Generated by Django 6.0.7 on 2026-07-28 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careerproject', '0002_resume_is_completed'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mentorstudent',
            unique_together={('mentor', 'student')},
        ),
    ]
