# Generated by Django 6.0.7 on 2026-07-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerproject', '0004_mentorfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='feedback_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='mentor_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
