# Generated by Django 6.0.7 on 2026-07-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerproject', '0005_resume_feedback_date_resume_mentor_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockinterview',
            name='feedback_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='mentor_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
