# Generated by Django 6.0.7 on 2026-07-29 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careerproject', '0006_mockinterview_feedback_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MentorStudent',
        ),
    ]
