# Generated by Django 6.0.7 on 2026-07-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerproject', '0007_delete_mentorstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
