# Generated by Django 6.0.7 on 2026-07-29 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careerproject', '0008_mentorprofile_last_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorprofile',
            name='last_seen',
        ),
    ]
