# Generated by Django 6.0.7 on 2026-07-29 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careerproject', '0009_remove_mentorprofile_last_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
