# Generated by Django 6.0.7 on 2026-07-30 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerproject', '0012_job_approval_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Learning', 'Learning'), ('Resume', 'Resume'), ('Portfolio', 'Portfolio'), ('Interview', 'Interview'), ('Job', 'Job'), ('Personal', 'Personal')], default='Learning', max_length=20)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('completed', models.BooleanField(default=False)),
                ('auto_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
