# Generated by Django 6.0.7 on 2026-07-30 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerproject', '0013_careertask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careertask',
            name='category',
            field=models.CharField(choices=[('Learning', 'Learning'), ('Resume', 'Resume'), ('Interview', 'Interview'), ('Job', 'Job'), ('Personal', 'Personal')], default='Learning', max_length=20),
        ),
        migrations.AlterField(
            model_name='careertask',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careerproject.studentprofile'),
        ),
    ]
