# Generated by Django 6.0.7 on 2026-07-30 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerproject', '0014_alter_careertask_category_alter_careertask_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careertask',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
