# Generated by Django 6.0.7 on 2026-08-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerproject', '0019_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='occupational_status',
            field=models.CharField(choices=[('Student', 'Student'), ('Unemployed', 'Unemployed'), ('Employed', 'Employed'), ('Career Break', 'Career Break')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='qualification',
            field=models.CharField(choices=[('10th', '10th'), ('12th', '12th'), ('Diploma', 'Diploma'), ('Graduate', 'Graduate'), ('Post Graduate', 'Post Graduate'), ('Others', 'Others')], max_length=30),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='skills',
            field=models.TextField(),
        ),
    ]
