# Generated by Django 6.0.7 on 2026-08-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerproject', '0020_alter_studentprofile_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumepersonal',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
